apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ezai-78b
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ai-gateway
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/llm-ly'
    targetRevision: HEAD
    path: llm-route-gen-chart
    helm:
      values: |
        spec:
          hostnames:
          - "blah.com"
          parentRefs:
            - name: https
              namespace: gloo-system
          rules:
          - backendRefName: openai
            pathPrefix: /openai
            routeOptionName: openai-route-policies
            useRandomPathPrefix: false
          - backendRefName: gemini
            pathPrefix: /gemini
            routeOptionName: gemini-route-policies
            useRandomPathPrefix: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
