name: ezai-https

namespace: ai-gateway

labels:
  example: custom-ai-gateway-route
  gateway: custom-https

hostnames:
  - "ezai.kapoozi.com"

parentRefs:
  - name: custom-https
    namespace: custom-gloo-system

rules:
  - backend:
      name: openai
    path: /openai
    routeOption: custom-openai-route-policies
  - backend:
      name: gemini
    path: /gemini
    routeOption: custom-gemini-route-policies
  - backend:
      name: claude
    path: /claude
    routeOption: custom-claude-route-policies
  - backend:
      name: mistral
    path: /mistral
    routeOption: custom-mistral-route-policies
