metadata:
  name: "" # Placeholder, will be replaced by generated name if not provided
  namespace: ai-gateway
  labels:
    example: ai-gateway-route
    gateway: https
spec:
  hostnames:
    - "ezai.kapoozi.com"
  parentRefs:
    - name: https
      namespace: gloo-system
  rules:
    - backendRefName: openai
      pathPrefix: /openai
      routeOptionName: openai-route-policies
    - backendRefName: gemini
      pathPrefix: /gemini
      routeOptionName: gemini-route-policies
    - backendRefName: claude
      pathPrefix: /claude
      routeOptionName: claude-route-policies
    - backendRefName: mistral
      pathPrefix: /mistral
      routeOptionName: mistral-route-policies
