apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ezai-route-yzK
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ai-gateway
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/llm-ly'
    targetRevision: HEAD
    path: llm-route-gen-chart
    helm:
      values: |
        metadata:
          name: ezai-https
          labels:
            example: ezai-route-yzK
        spec:
          hostnames:
            - "ezai.kapoozi.com"
          parentRefs:
            - name: https
              namespace: gloo-system
          rules:
            - backendRefName:               pathPrefix: /              routeOptionName:   syncPolicy:
    automated:
      prune: true
      selfHeal: true
