apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-gateway-route
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ai-gateway
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/llm-ly'
    targetRevision: HEAD
    path: llm-route-gen-chart
    helm:
      values: |
        metadata:
          name: ai-gateway-https
          labels:
            example: ai-gateway-route
        spec:
          hostnames:
            - "ai-gateway.kapoozi.com"
          parentRefs:
            - name: https
              namespace: gloo-system
          rules:
            - backendRefName: openai
              pathPrefix: /openai
              routeOptionName: openai-route-policies
            - backendRefName: gemini
              pathPrefix: /gemini
              routeOptionName: gemini-route-policies
            - backendRefName: claude
              pathPrefix: /claude
              routeOptionName: claude-route-policies
            - backendRefName: mistral
              pathPrefix: /mistral
              routeOptionName: mistral-route-policies        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
