apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ .Values.name | default "ezai-https" }}
  namespace: {{ .Values.namespace | default "ai-gateway" }}
  labels:
    example: {{ .Values.labels.example | default "ai-gateway-route" }}
    gateway: {{ .Values.labels.gateway | default "https" }}
spec:
  hostnames:
  {{- range .Values.hostnames | default (list "ezai.kapoozi.com") }}
  - "{{ . }}"
  {{- end }}
  parentRefs:
  {{- range .Values.parentRefs | default (list (dict "name" "https" "namespace" "gloo-system")) }}
    - name: {{ .name | default "https" }}
      namespace: {{ .namespace | default "gloo-system" }}
  {{- end }}
  rules:
  {{- range .Values.rules | default (list (dict "backend" (dict "group" "gloo.solo.io" "kind" "Upstream" "name" "openai") "path" "/openai" "routeOption" "openai-route-policies") (dict "backend" (dict "group" "gloo.solo.io" "kind" "Upstream" "name" "gemini") "path" "/gemini" "routeOption" "gemini-route-policies") (dict "backend" (dict "group" "gloo.solo.io" "kind" "Upstream" "name" "claude") "path" "/claude" "routeOption" "claude-route-policies") (dict "backend" (dict "group" "gloo.solo.io" "kind" "Upstream" "name" "mistral") "path" "/mistral" "routeOption" "mistral-route-policies"))) }}
    - backendRefs:
        - group: {{ .backend.group | default "gloo.solo.io" }}
          kind: {{ .backend.kind | default "Upstream" }}
          name: {{ .backend.name | default "openai" }}
      matches:
        - path:
            type: PathPrefix
            value: {{ .path | default "/openai" }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.solo.io
            kind: RouteOption
            name: {{ .routeOption | default "openai-route-policies" }}
  {{- end }}
