{{- $generatedName := printf "ezai-%s" (randAlphaNum 8 | lower) }}
{{- $name := .Values.metadata.name | default $generatedName }}
{{- $namespace := .Release.Namespace }}
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{ $name }}
  namespace: {{ .Values.metadata.namespace | default $namespace }}
  labels:
{{- range $key, $value := .Values.metadata.labels }}
    {{ $key }}: {{ $value }}
{{- end }}
spec:
  hostnames:
{{- range .Values.spec.hostnames }}
    - {{ . }}
{{- end }}
  parentRefs:
{{- range .Values.spec.parentRefs }}
    - name: {{ .name | default "https" }}
      namespace: {{ .namespace | default "gloo-system" }}
{{- end }}
  rules:
{{- range .Values.spec.rules }}
    - backendRefs:
        - group: gloo.solo.io
          kind: Upstream
          name: {{ .backendRefName }}
      matches:
        - path:
            type: PathPrefix
            value: {{ .pathPrefix }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: gateway.solo.io
            kind: RouteOption
            name: {{ .routeOptionName }}
{{- end }}
