apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: ezai-https
  namespace: ai-gateway
  labels:
    example: ai-gateway-route
    gateway: https
spec:
  hostnames:
  {{- toYaml .Values.hostnames | nindent 4 }}
  parentRefs:
    - name: {{ .Values.parentRef.name }}
      namespace: {{ .Values.parentRef.namespace }}
  rules:
    {{- range .Values.routes }}
    - backendRefs:
        - group: {{ .backendGroup }}
          kind: {{ .backendKind }}
          name: {{ .name }}
      matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
      filters:
        - type: ExtensionRef
          extensionRef:
            group: {{ .routeOptionGroup }}
            kind: {{ .routeOptionKind }}
            name: {{ .name }}-route-policies
    {{- end }}
