name: Delete Proxy Action

on:
  workflow_dispatch:
    inputs:
      suffix:
        description: 'Suffix of the application name to delete'
        required: true
        type: string
      webhook_url:
        description: 'Webhook URL to call on completion'
        required: false
        type: string

jobs:
  delete-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find and delete manifest file
        id: find_and_delete_manifest
        run: |  
          SUFFIX=${{ github.event.inputs.suffix }}
          FILE_PATH=$(find environments/kapoozi/ai-gateway-routes/base/ -name "*${SUFFIX}.yaml")

          if [ -z "$FILE_PATH" ]; then
            echo "No file found with suffix $SUFFIX"
            exit 1
          else
            git rm "$FILE_PATH"
            echo "Deleted $FILE_PATH"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Deleted llm proxy manifest with suffix ${{ github.event.inputs.suffix }} using GitHub Action"
          git push origin HEAD

      - name: Send webhook notification
        if: ${{ github.event.inputs.webhook_url != '' }}
        uses: distributhor/workflow-webhook@v1
        with:
          url: ${{ github.event.inputs.webhook_url }}
          method: POST
          headers: |
            Content-Type: application/json
          body: |
            {
              "status": "success",
              "message": "Deleted proxy with suffix ${{ github.event.inputs.suffix }}",
              "repository": "${{ github.repository }}",
              "commit_sha": "${{ github.sha }}"
            }
