name: Delete Proxy Action

on:
  workflow_dispatch:
    inputs:
      route_id:
        description: 'Route ID to delete'
        required: true
        type: string
      webhook_url:
        description: 'Webhook URL to call on completion'
        required: false
        type: string

jobs:
  delete-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find and delete manifest file
        id: find_and_delete_manifest
        run: |  
          ROUTE_ID=${{ github.event.inputs.route_id }}
          FILE_PATH=$(find environments/kapoozi/ai-gateway-routes/base/ -name "*${ROUTE_ID}.yaml")

          if [ -z "$FILE_PATH" ]; then
            echo "No file found with route_id $ROUTE_ID"
            exit 1
          else
            git rm "$FILE_PATH"
            echo "Deleted $FILE_PATH"
          fi

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git commit -m "Deleted llm proxy manifest with route_id ${{ github.event.inputs.route_id }} using GitHub Action"
          git push origin HEAD

      - name: Send webhook notification
        run: |
          curl -v -X POST -d '{ "status": "success," "action": "delete" }' ${{GitHub.event.inputs.webhook_url }}
      
