name: Generate Proxy Action

on:
  workflow_dispatch:
    inputs:
      routes:
        description: 'Select the route options (comma-separated)'
        required: true
        default: 'openai,gemini,claude,mistral'
        type: string
      hostname:
        description: 'Hostname (optional)'
        required: false
        type: string
      use_random_path_prefix:
        description: 'Use random path prefix (true/false)'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render manifest based on input
        id: render_manifest
        run: |
          # Generate a random string for the application name
          RANDOM_STRING=$(openssl rand -hex 2 | cut -c1-3)
          
          ROUTES=${{ github.event.inputs.routes }}
          HOSTNAME=${{ github.event.inputs.hostname }}
          USE_RANDOM_PATH_PREFIX=${{ github.event.inputs.use_random_path_prefix }}
          IFS=',' read -ra ROUTE_ARRAY <<< "$ROUTES"

          RULES=""
          for ROUTE_NAME in "${ROUTE_ARRAY[@]}"; do
            case $ROUTE_NAME in
              "openai")
                BACKEND_REF_NAME="openai"
                PATH_PREFIX="/openai"
                ROUTE_OPTION_NAME="openai-route-policies"
                ;;
              "gemini")
                BACKEND_REF_NAME="gemini"
                PATH_PREFIX="/gemini"
                ROUTE_OPTION_NAME="gemini-route-policies"
                ;;
              "claude")
                BACKEND_REF_NAME="claude"
                PATH_PREFIX="/claude"
                ROUTE_OPTION_NAME="claude-route-policies"
                ;;
              "mistral")
                BACKEND_REF_NAME="mistral"
                PATH_PREFIX="/mistral"
                ROUTE_OPTION_NAME="mistral-route-policies"
                ;;
            esac

            RULES="${RULES}
                    - backendRefName: $BACKEND_REF_NAME
                      pathPrefix: $PATH_PREFIX
                      routeOptionName: $ROUTE_OPTION_NAME
                      useRandomPathPrefix: $USE_RANDOM_PATH_PREFIX"
          done

          if [ -n "$HOSTNAME" ]; then
            HOSTNAMES="hostnames:
                    - \"$HOSTNAME\""
          else
            HOSTNAMES=""
          fi

          FILE_PATH="environments/kapoozi/ai-gateway-routes/base/ezai-${RANDOM_STRING}.yaml"

          cat <<EOF > $FILE_PATH
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ezai-${RANDOM_STRING}
            namespace: argocd
            finalizers:
              - resources-finalizer.argocd.argoproj.io
          spec:
            project: default
            destination:
              namespace: ai-gateway
              server: "https://kubernetes.default.svc"
            source:
              repoURL: 'https://github.com/ably77/llm-ly'
              targetRevision: HEAD
              path: llm-route-gen-chart
              helm:
                values: |
                  spec:
                    ${HOSTNAMES}
                    parentRefs:
                      - name: https
                        namespace: gloo-system
                    rules:${RULES}
            syncPolicy:
              automated:
                prune: true
                selfHeal: true
          EOF

          echo "FILE_PATH=$FILE_PATH" >> $GITHUB_ENV

      - name: Update kustomization.yaml
        run: |
          KUSTOMIZATION_PATH="environments/kapoozi/ai-gateway-routes/base/kustomization.yaml"
          echo "Adding $FILE_PATH to $KUSTOMIZATION_PATH"
          echo "resources:" > $KUSTOMIZATION_PATH
          echo "- ${FILE_PATH}" >> $KUSTOMIZATION_PATH

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update rendered manifest and kustomization
          file_pattern: |
            environments/kapoozi/ai-gateway-routes/base/rendered-manifest-*.yaml
            environments/kapoozi/ai-gateway-routes/base/kustomization.yaml
