name: Add YAML file

on:
  push:
    branches:
      - main

jobs:
  add_yaml_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create YAML file
      run: |
        mkdir -p environments/kapoozi/ai-gateway-routes
        cat <<EOF > environments/kapoozi/ai-gateway-routes/application.yaml
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: ezai-route
          namespace: argocd
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: default
          destination:
            namespace: ai-gateway
            server: "https://kubernetes.default.svc"
          source:
            repoURL: 'https://github.com/ably77/llm-ly'
            targetRevision: HEAD
            path: llm-route-gen-chart
            helm:
              values: |
                metadata:
                  name: ezai-https
                  labels:
                    example: ezai-route
                spec:
                  hostnames:
                    - "ezai.kapoozi.com"
                  parentRefs:
                    - name: https
                      namespace: gloo-system
                  rules:
                    - backendRefName: openai
                      pathPrefix: /openai
                      routeOptionName: openai-route-policies
                    - backendRefName: gemini
                      pathPrefix: /gemini
                      routeOptionName: gemini-route-policies
                    - backendRefName: claude
                      pathPrefix: /claude
                      routeOptionName: claude-route-policies
                    - backendRefName: mistral
                      pathPrefix: /mistral
                      routeOptionName: mistral-route-policies        
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
        EOF

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add environments/kapoozi/ai-gateway-routes/application.yaml
        git commit -m "Add application.yaml file"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
