name: Add YAML file with variable replacement

on:
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Hostname'
        required: false
      namespace:
        description: 'Namespace'
        required: false
        default: 'argocd'
      app_name:
        description: 'Application Name'
        required: false
        default: 'ezai-route'
      gateway_namespace:
        description: 'Gateway Namespace'
        required: false
        default: 'gloo-system'
      upstream_ref_openai:
        description: 'Upstream Ref OpenAI'
        required: false
        default: 'openai'
      upstream_ref_gemini:
        description: 'Upstream Ref Gemini'
        required: false
        default: 'gemini'
      upstream_ref_claude:
        description: 'Upstream Ref Claude'
        required: false
        default: 'claude'
      upstream_ref_mistral:
        description: 'Upstream Ref Mistral'
        required: false
        default: 'mistral'
      route_option_openai:
        description: 'Route Option OpenAI'
        required: false
        default: 'openai-route-policies'
      route_option_gemini:
        description: 'Route Option Gemini'
        required: false
        default: 'gemini-route-policies'
      route_option_claude:
        description: 'Route Option Claude'
        required: false
        default: 'claude-route-policies'
      route_option_mistral:
        description: 'Route Option Mistral'
        required: false
        default: 'mistral-route-policies'

jobs:
  add_yaml_file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate random suffix
      id: suffix
      run: echo "::set-output name=suffix::$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 3)"

    - name: Set full application name
      run: echo "FULL_APP_NAME=${{ github.event.inputs.app_name }}-${{ steps.suffix.outputs.suffix }}" >> $GITHUB_ENV

    - name: Create YAML file with placeholders
      run: |
        mkdir -p environments/kapoozi/ai-gateway-routes
        cat <<EOF > environments/kapoozi/ai-gateway-routes/application.yaml
        apiVersion: argoproj.io/v1alpha1
        kind: Application
        metadata:
          name: ${{ env.FULL_APP_NAME }}
          namespace: ${{ github.event.inputs.namespace }}
          finalizers:
            - resources-finalizer.argocd.argoproj.io
        spec:
          project: default
          destination:
            namespace: ai-gateway
            server: "https://kubernetes.default.svc"
          source:
            repoURL: 'https://github.com/ably77/llm-ly'
            targetRevision: HEAD
            path: llm-route-gen-chart
            helm:
              values: |
                metadata:
                  name: ezai-https
                  labels:
                    example: ${{ env.FULL_APP_NAME }}
                spec:
                  hostnames:
                    - "${{ github.event.inputs.hostname }}"
                  parentRefs:
                    - name: https
                      namespace: ${{ github.event.inputs.gateway_namespace }}
                  rules:
                    - backendRefName: ${{ github.event.inputs.upstream_ref_openai }}
                      pathPrefix: /openai
                      routeOptionName: ${{ github.event.inputs.route_option_openai }}
                    - backendRefName: ${{ github.event.inputs.upstream_ref_gemini }}
                      pathPrefix: /gemini
                      routeOptionName: ${{ github.event.inputs.route_option_gemini }}
                    - backendRefName: ${{ github.event.inputs.upstream_ref_claude }}
                      pathPrefix: /claude
                      routeOptionName: ${{ github.event.inputs.route_option_claude }}
                    - backendRefName: ${{ github.event.inputs.upstream_ref_mistral }}
                      pathPrefix: /mistral
                      routeOptionName: ${{ github.event.inputs.route_option_mistral }}        
          syncPolicy:
            automated:
              prune: true
              selfHeal: true
        EOF

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add environments/kapoozi/ai-gateway-routes/application.yaml
        git commit -m "Add application.yaml file with replaced variables"
        git push https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/ably77/llm-ly.git
