name: Configure Application Manifest

on:
  workflow_dispatch:
    inputs:
      routes:
        description: 'Select the route options (comma-separated)'
        required: true
        default: 'openai,gemini,claude,mistral'
        type: string

jobs:
  update-manifest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render manifest based on input
        id: render_manifest
        run: |
          ROUTES=${{ github.event.inputs.routes }}
          IFS=',' read -ra ROUTE_ARRAY <<< "$ROUTES"

          RULES=""
          for ROUTE_NAME in "${ROUTE_ARRAY[@]}"; do
            case $ROUTE_NAME in
              "openai")
                BACKEND_REF_NAME="openai"
                PATH_PREFIX="/openai"
                ROUTE_OPTION_NAME="openai-route-policies"
                ;;
              "gemini")
                BACKEND_REF_NAME="gemini"
                PATH_PREFIX="/gemini"
                ROUTE_OPTION_NAME="gemini-route-policies"
                ;;
              "claude")
                BACKEND_REF_NAME="claude"
                PATH_PREFIX="/claude"
                ROUTE_OPTION_NAME="claude-route-policies"
                ;;
              "mistral")
                BACKEND_REF_NAME="mistral"
                PATH_PREFIX="/mistral"
                ROUTE_OPTION_NAME="mistral-route-policies"
                ;;
            esac

            RULES="${RULES}
          - backendRefName: $BACKEND_REF_NAME
            pathPrefix: $PATH_PREFIX
            routeOptionName: $ROUTE_OPTION_NAME
            useRandomPathPrefix: true"
          done

          cat <<EOF > rendered-manifest.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: random-generated-route
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ai-gateway
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/llm-ly'
    targetRevision: HEAD
    path: llm-route-gen-chart
    helm:
      values: |
        spec:
          parentRefs:
            - name: https
              namespace: gloo-system
          rules:${RULES}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update rendered manifest
          file_pattern: rendered-manifest.yaml
