name: Add YAML file with variable replacement

on:
  workflow_dispatch:
    inputs:
      backend:
        description: 'Select Backend'
        required: true
        type: choice
        options:
          - openai
          - gemini
          - claude
          - mistral

jobs:
  add_yaml_file:
    runs-on: ubuntu-latest

    env:
      NAMESPACE: 'argocd'
      GATEWAY_NAMESPACE: 'gloo-system'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate random suffix
      id: suffix
      run: echo "::set-output name=suffix::$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 3)"

    - name: Set full application name
      run: echo "FULL_APP_NAME=ezai-route-${{ steps.suffix.outputs.suffix }}" >> $GITHUB_ENV

    - name: Create YAML file with placeholders
      run: |
        mkdir -p environments/kapoozi/ai-gateway-routes
        cat <<EOF > environments/kapoozi/ai-gateway-routes/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ env.FULL_APP_NAME }}
  namespace: ${{ env.NAMESPACE }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ai-gateway
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/llm-ly'
    targetRevision: HEAD
    path: llm-route-gen-chart
    helm:
      values: |
        metadata:
          name: ezai-https
          labels:
            example: ${{ env.FULL_APP_NAME }}
        spec:
EOF

        if [ -n "${{ github.event.inputs.hostname }}" ]; then
          echo "          hostnames:
            - \"${{ github.event.inputs.hostname }}\"" >> environments/kapoozi/ai-gateway-routes/application.yaml
        fi

        case "${{ github.event.inputs.backend }}" in
          "openai")
            echo "          rules:
            - backendRefName: openai
              pathPrefix: /openai
              routeOptionName: openai-route-policies" >> environments/kapoozi/ai-gateway-routes/application.yaml
            ;;
          "gemini")
            echo "          rules:
            - backendRefName: gemini
              pathPrefix: /gemini
              routeOptionName: gemini-route-policies" >> environments/kapoozi/ai-gateway-routes/application.yaml
            ;;
          "claude")
            echo "          rules:
            - backendRefName: claude
              pathPrefix: /claude
              routeOptionName: claude-route-policies" >> environments/kapoozi/ai-gateway-routes/application.yaml
            ;;
          "mistral")
            echo "          rules:
            - backendRefName: mistral
              pathPrefix: /mistral
              routeOptionName: mistral-route-policies" >> environments/kapoozi/ai-gateway-routes/application.yaml
            ;;
        esac

        cat <<EOF >> environments/kapoozi/ai-gateway-routes/application.yaml
          parentRefs:
            - name: https
              namespace: ${{ env.GATEWAY_NAMESPACE }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add environments/kapoozi/ai-gateway-routes/application.yaml
        git commit -m "Add application.yaml file with replaced variables"
        git push https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/ably77/llm-ly.git
