name: Add YAML file with variable replacement

on:
  workflow_dispatch:
    inputs:
      upstream_options:
        description: 'Choose one or more upstream options (comma separated)'
        required: true
        default: 'openai'
        type: string

jobs:
  add_yaml_file:
    runs-on: ubuntu-latest

    env:
      HOSTNAME: 'ezai.kapoozi.com'
      NAMESPACE: 'argocd'
      APP_NAME: 'ezai-route'
      GATEWAY_NAMESPACE: 'gloo-system'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Generate random suffix
      id: suffix
      run: echo "::set-output name=suffix::$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 3)"

    - name: Set full application name
      run: echo "FULL_APP_NAME=${APP_NAME}-$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c 3)" >> $GITHUB_ENV

    - name: Create YAML file with placeholders
      run: |
        mkdir -p environments/kapoozi/ai-gateway-routes
        cat <<EOF > environments/kapoozi/ai-gateway-routes/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ env.FULL_APP_NAME }}
  namespace: ${NAMESPACE}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: ai-gateway
    server: "https://kubernetes.default.svc"
  source:
    repoURL: 'https://github.com/ably77/llm-ly'
    targetRevision: HEAD
    path: llm-route-gen-chart
    helm:
      values: |
        metadata:
          name: ezai-https
          labels:
            example: ${{ env.FULL_APP_NAME }}
        spec:
          hostnames:
            - "${HOSTNAME}"
          parentRefs:
            - name: https
              namespace: ${GATEWAY_NAMESPACE}
          rules:
EOF

    - name: Set selected upstream variables
      run: |
        IFS=',' read -ra ADDR <<< "${{ github.event.inputs.upstream_options }}"
        for i in "${ADDR[@]}"; do
          case $i in
            "openai")
              echo "            - backendRefName: openai" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              pathPrefix: /openai" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              routeOptionName: openai-route-policies" >> environments/kapoozi/ai-gateway-routes/rules.txt
              ;;
            "gemini")
              echo "            - backendRefName: gemini" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              pathPrefix: /gemini" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              routeOptionName: gemini-route-policies" >> environments/kapoozi/ai-gateway-routes/rules.txt
              ;;
            "claude")
              echo "            - backendRefName: claude" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              pathPrefix: /claude" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              routeOptionName: claude-route-policies" >> environments/kapoozi/ai-gateway-routes/rules.txt
              ;;
            "mistral")
              echo "            - backendRefName: mistral" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              pathPrefix: /mistral" >> environments/kapoozi/ai-gateway-routes/rules.txt
              echo "              routeOptionName: mistral-route-policies" >> environments/kapoozi/ai-gateway-routes/rules.txt
              ;;
          esac
        done

    - name: Append rules and syncPolicy to YAML file
      run: |
        cat environments/kapoozi/ai-gateway-routes/rules.txt >> environments/kapoozi/ai-gateway-routes/application.yaml
        cat <<EOF >> environments/kapoozi/ai-gateway-routes/application.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
EOF

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add environments/kapoozi/ai-gateway-routes/application.yaml
        git commit -m "Add application.yaml file with replaced variables"
        git push https://github-actions:${{ secrets.PAT_TOKEN }}@github.com/ably77/llm-ly.git
